# Generated by Django 2.0.5 on 2018-05-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Alpha'), ('2', 'Beta'), ('3', 'Delta'), ('4', 'Epsilon'), ('5', 'Zeta'), ('6', 'Eta'), ('7', 'Iota'), ('8', 'Nu'), ('9', 'Omega'), ('10', 'Alpha-Alpha')], max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=50)),
                ('street_number', models.IntegerField()),
                ('zip_Code', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=20)),
                ('sir_name', models.CharField(help_text='Enter last name', max_length=20)),
                ('relationship', models.CharField(choices=[('1', 'Brother'), ('2', 'Pledge'), ('3', 'President'), ('4', 'Vice President'), ('5', 'Tresurer'), ('6', 'Sargent-at-Arms'), ('7', 'Secretary'), ('8', 'Social-Chair'), ('9', 'Philantropy-Chair'), ('10', 'Recruitment-Chair'), ('11', 'Pledge-Education-Chair')], max_length=25)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'Alumni')], max_length=20)),
                ('activation_date', models.DateTimeField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chapter.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='MemberChurch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pastor', models.CharField(max_length=50)),
                ('synod', models.CharField(choices=[('1', 'LCMS'), ('2', 'ELCA'), ('3', 'NALC'), ('4', 'WELS'), ('5', 'OTHER')], max_length=5)),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chapter.ContactInformation')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='church',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chapter.MemberChurch'),
        ),
        migrations.AddField(
            model_name='member',
            name='contact_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chapter.ContactInformation'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='contact_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chapter.ContactInformation'),
        ),
    ]
